# Structure:
#
# foo_controller:
#     pattern: /foo
#     defaults: { controller: foo_sevice:method }
#
# If no method is specified, it will require a method named "handle"
#
# The above will be accessed via app.php/foo and it will instantiate the
# foo_service service and call the "method" method.
