# Structure:
#
# foo_controller:
#     pattern: /foo
#     defaults: { _controller: foo_sevice:method }
#
# The above will be accessed via app.php?controller=foo and it will
# instantiate the "foo_service" service and call the "method" method.
#

board_index_controller:
    pattern: /{index}
    defaults: { _controller: index.controller:main }
    requirements:
        # match '/index' or '/' for path
        index: (index|)

viewtopic_controller:
    pattern: /topic/{topic_id}/{view}
    defaults: { _controller: topic.controller:main, view: }
    requirements:
        # Must be one or more digits followed by an optional URL slug
        # containing lowercase letters, numbers, and dashes
        topic_id: ([0-9]+)(-[a-z0-9-]+)?
        # match one of 'print', 'unread', 'next', 'prev' or empty
        view: (print|unread|next|prev|)
