# Structure:
#
# foo_controller:
#     service: service.name
#
# -- OR --
#
# foo_controller:
#     class: phpbb_ext_example_foo_controller
#
# The above will be accessed via app.php?controller=foo_controller
