# Structure:
#
# foo_controller:
#     pattern: /foo
#     defaults: { _controller: foo_sevice:method }
#
# The above will be accessed via app.php?controller=foo and it will
# instantiate the "foo_service" service and call the "method" method.
#

board_index_controller:
    pattern: /{index}
    defaults: { _controller: index.controller:main }
    requirements:
        # match '/index' or '/' for path
        index: (index|)
